name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint (ruff)
        run: |
          pip install ruff
          ruff check .

      - name: Import smoke test
        run: |
          python - << 'PY'
          import importlib
          for m in ["streamlit","utils.llm","utils.ui","utils.theme_presets"]:
              importlib.import_module(m)
          print("Imports OK")
          PY
